# Generated by Django 2.2.16 on 2022-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220428_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-08-24T14:15:22Z', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
