# Generated by Django 2.2.16 on 2022-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20220428_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.TimeField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
